# Generated by Django 3.2.7 on 2021-10-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0002_auto_20211008_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha registro')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
