# Generated by Django 3.2.7 on 2021-10-09 02:13

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0004_auto_20211008_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_servicio',
            name='tipo',
            field=models.CharField(default=builtins.dir, max_length=50),
            preserve_default=False,
        ),
    ]
