# Generated by Django 3.2.7 on 2021-10-09 02:15

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0005_producto_servicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_servicio',
            name='nombre',
            field=models.CharField(default=builtins.dir, max_length=80),
            preserve_default=False,
        ),
    ]
