# Generated by Django 3.2.7 on 2021-10-09 02:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0006_producto_servicio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_servicio',
            name='especificacion_tecnica',
            field=models.CharField(default=builtins.dir, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto_servicio',
            name='margen',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='producto_servicio',
            name='unidad_medida',
            field=models.CharField(default=builtins.dir, max_length=10),
            preserve_default=False,
        ),
    ]
