# Generated by Django 3.2.7 on 2021-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0009_auto_20211009_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_ruc_dni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('tipo_documento', models.IntegerField(max_length=2)),
                ('numero_documento', models.CharField(max_length=11)),
                ('estado', models.CharField(max_length=20)),
                ('condicion', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=500)),
                ('ubigeo', models.CharField(max_length=8)),
                ('via_tipo', models.CharField(max_length=15)),
                ('via_nombre', models.CharField(max_length=30)),
                ('zona_codigo', models.CharField(max_length=30)),
                ('zona_tipo', models.CharField(max_length=30)),
                ('numero', models.IntegerField(max_length=10)),
                ('interior', models.CharField(max_length=30)),
                ('lote', models.CharField(max_length=30)),
                ('dpto', models.CharField(max_length=30)),
                ('manzana', models.CharField(max_length=30)),
                ('kilometro', models.CharField(max_length=30)),
                ('distrito', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto_servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
