# Generated by Django 3.1.1 on 2021-10-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0011_auto_20211010_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_empresa_catalogo_ruc_dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_empresa_catalogo_ruc_dni', to='sistema_cotizador_app.catalogo_ruc_dni', verbose_name='empresa catalogo ruc dni'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_persona_catalogo_ruc_dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_persona_catalogo_ruc_dni', to='sistema_cotizador_app.catalogo_ruc_dni', verbose_name='persona catalogo ruc dni'),
        ),
    ]
