# Generated by Django 3.1.1 on 2021-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0014_auto_20211010_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_ruc_dni',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
