# Generated by Django 3.2.7 on 2021-10-10 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema_cotizador_app', '0016_auto_20211010_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador_maestro',
            name='id_catalogo_tipo_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_catalogo_tipo_cambio', to='sistema_cotizador_app.catalogo_tipo_cambio', verbose_name='id_catalogo_tipo_cambio'),
        ),
        migrations.AddField(
            model_name='cotizador_maestro',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_cotizador_app.cliente', verbose_name='id cliente'),
        ),
        migrations.AlterField(
            model_name='cotizador_maestro',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_usuario', to=settings.AUTH_USER_MODEL, verbose_name='id usuario'),
        ),
    ]
