# Generated by Django 3.2.7 on 2021-10-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0017_auto_20211010_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='id_cotizador_maestro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_cotizador_app.cotizador_maestro', verbose_name='id cotizador maestro'),
        ),
        migrations.CreateModel(
            name='cotizador_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cotizador_maestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_cotizador_app.cotizador_maestro', verbose_name='id cotizador maestro')),
                ('id_producto_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_cotizador_app.producto_servicio', verbose_name='id producto servicio')),
            ],
        ),
    ]
