# Generated by Django 3.2.7 on 2021-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizador_app', '0019_alter_cotizador_detalle_id_cotizador_maestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_tipo_cambio',
            name='fecha',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
